# Streamlit Cloud Secrets Configuration
# Copy this content to your Streamlit Cloud app settings

# OpenAI API Key (Required for AI features)
OPENAI_API_KEY = "your_openai_api_key_here"

# CRM Configuration
CRM_NAME = "Bumuk Library CRM"
CRM_VERSION = "1.0.0"

# Database Configuration (Optional - uses defaults)
# DATABASE_PATH = "crm_database.db"

# Security Settings (Optional - uses defaults)
# SESSION_TIMEOUT_HOURS = 24
# MAX_LOGIN_ATTEMPTS = 5
